name: Deploy QA to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mtt-ui-qa repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Clean and Build Angular app
        run: |
          rm -rf dist/
          npx ng build appoinement-admin --configuration qa --base-href=/

      - name: Prepare extra files
        run: |
          cp dist/appoinement-admin/browser/index.html dist/appoinement-admin/browser/404.html
          echo "qa.sadisha.org" > dist/appoinement-admin/browser/CNAME

      - name: Deploy to gh-pages
        run: |
          cd dist/appoinement-admin/browser
          git init
          git config user.name "gopi6sigma"
          git config user.email "gopi6sigma@gmail.com"
          git add .
          git commit -m "Deploy QA from mtt-ui-qa: $(date +'%Y-%m-%d %H:%M:%S')"
          git branch -M gh-pages
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/AravindAttepu/mtt-ui-qa.git
          git push -f origin gh-pages
